spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver

  jpa:
    database: H2
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      platform: test

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: test
            client-secret: test
            scope: test
            redirect-uri: test
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization_uri: test
            token_uri: test
            user-info-uri: test
            user_name_attribute: test

jwt:
  issuer: test
  secret-key: XtvCnK/2CRsblAWCjeh22VAyXGjszJLR4xVQJ8CNTVk=
  access-token:
    expire-length: 3600000
  refresh-token:
    expire-length: 3600000

cloud:
  aws:
    s3:
      bucket: test
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
