spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver

  jpa:
    database: H2
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: test
            client-secret: test
            scope: profile_nickname, profile_image, account_email, birthday
            redirect-uri: http://localhost:8080/login/oauth2/code/{registrationId}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

jwt:
  issuer: test
  secret-key: XtvCnK/2CRsblAWCjeh22VAyXGjszJLR4xVQJ8CNTVk=
  access-token:
    expire-length: 3600000
  refresh-token:
    expire-length: 3600000

cloud:
  aws:
    s3:
      bucket: test
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
